### ISSUE TITLE
Audio error

### ISSUE THREAD

**Issue by DelfinSmile29** [Wolfyxon/HeroOfTheEarth-game#1]
If you open the game with Winrar without extracting the file first, the audio service will break down and all audio will stop working. You need to restart your computer.

**Comment by WolfGames** [comment]
Thanks for first bug report.
We will install WinRar on virtual Windows machine and test it.
But anyway we don't know how to fix this.
Wait for next version.

**Comment by WolfGames** [comment]
It's problem with your system, sound card or WinRaR
When i was testing it didn't got this bug.
Maybe this will help you:
https://answers.microsoft.com/en-us/windows/forum/windows_10-hardware-winpc/audio-stops-working-after-opening-certain-software/02367d69-8240-4935-933e-1a0309ea5d2b

**Comment by WolfGames** [comment]
Hello again  
It must be driver problem.
In project default sound driver is set to WASPI (or wsapi I don't remember lol) 
Can you say your sound driver name?

**Comment by WolfGames** [comment]
Hi
I've just experienced this problem some minutes ago and I think it's something with godot engine.
It happens randomly ¯\_(ツ)_/¯
